### ISSUE TITLE
Feature suggestion: command add --dry-run

### ISSUE THREAD

**Issue by jneubert** [gbv/wdmapper#12]
When I have an externally crafted mapping file, I currently cannot see a way to evaluate which of these mappings would "work" for wikidata - meaning: have a matching property value for the WDSOURCEPROPERTY column. The `diff` command does not provide this, the description of the not-yet-implemented `check` command seems to aim at a different use case. 

An `add --dry-run` could provide the information where a WDTARGETPROPERTY would be added (plus warnings, where a different WDTARGETPROPERTY value is already attached, plus perhaps - with `--verbose` - messages where the actual property value is already in place). 

In production use, the function would be very helpful to check input files in advance and avoid costly mistakes. I suppose, it could be useful in the development of wdmaper, too, because it can be run on live data again and again.

**Comment by nichtich** [comment]
already implemented (but not used as long as #24 has not been implemented)
