### ISSUE TITLE
Add option to allow properties of other datatype than external identifier

### ISSUE THREAD

**Issue by nichtich** [gbv/wdmapper#14]
Some properties of type string or item can also be used for mapping.

**Comment by nichtich** [comment]
Allowed properties could also be reduced for instance to properties for authority control for people
<http://www.wikidata.org/wiki/Q19595382>

**Comment by jneubert** [comment]
That's a tricky one. Some of the most valuable properties (GND, VIAF, or ISNI) - are not part of this subset, because they cover other entity types too. [See list here](http://zbw.eu/beta/sparql-lab/result?resultRef=https://api.github.com/repos/zbw/sparql-queries/contents/wikidata/results/count_by_authority_for_persons.wikidata_2016-11-07.json)

**Comment by nichtich** [comment]
Wikidata item could easily be filtered to instances of a given class such as https://www.wikidata.org/wiki/Q215627 (person) and its subclasses. Wikidata items, however, sometimes lack the 'instance-of' statement.

**Comment by nichtich** [comment]
Q215627 (person) illustrates the problem as it includes organizations (legal persons), better use Q5 (human).

I added option `--type` in release 0.0.7 but it is ignored for command `check`. I am not sure whether this is right, so I keep this issue open.

**Comment by jneubert** [comment]
Not sure if I understand this issue. Or are there multiple issues? 

What should be acchieved by the `--type` option?

**Comment by jneubert** [comment]
Re. identifying persons: P31 Q5 worked quite well for me, I didn't come across anybody excluded by that restriction.

**Comment by jneubert** [comment]
BTW: There seems to be an ongoing (?) [discussion/effort to convert string properties to externalId](https://www.wikidata.org/wiki/Wikidata:Conversion_of_datatype_to_external-id)

**Comment by nichtich** [comment]
The current version supports Wikidata properties of type string as well. Wikidata properties of type item also exist for some authority files but these are not supported by wdmapper.
