### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jneubert** [gbv/wdmapper#3]
I had installed the version from this noon. The script was executable, but gave an error when I tried to apply it. 

Now I removed the installed files (`python setup.py install --record files.txt`), and installed  cc4c990 again from scratch. Now I don't even get the help info:
```
[root@nbt4 bin]# wdmapper -h
Traceback (most recent call last):
  File "/usr/bin/wdmapper", line 9, in <module>
    load_entry_point('wdmapper==0.0.0', 'console_scripts', 'wdmapper')()
TypeError: main() takes exactly 1 argument (0 given)
```
Python version is 2.7.5

**Comment by nichtich** [comment]
Should be fixed with https://github.com/gbv/wdmapper/commit/3521342ffdc8e8af3a24fd858d001270fc5bafe6
