### ISSUE TITLE
wdmapper get not working with two properties

### ISSUE THREAD

**Issue by jneubert** [gbv/wdmapper#6]
The example command `wdmapper get P214 P2428 --limit 10` results in
```
source, target, annotation
sourceId, targetId, Q18430
sourceId, targetId, Q100689
sourceId, targetId, Q131112
sourceId, targetId, Q173994
sourceId, targetId, Q191020
sourceId, targetId, Q434509
sourceId, targetId, Q502557
sourceId, targetId, Q925174
sourceId, targetId, Q1153459
sourceId, targetId, Q1189225
```
Python 2.7.5 and d9e46a0

**Comment by nichtich** [comment]
Thanks, fixed in the dev branch. Try also

    wdmapper get P214 P2428 --limit 10 -t beacon

Command `diff` to compare given mappings from file and mappings in Wikidata should be implemented next.
